export  const INCREMENT_COUNTER ="INCREMENT COUNTER"
export  const DECREMENT_COUNTER ="DECREMENT COUNTER"
export  const INCREMENT_COUNTER_ASYNC ="INCREMENT_COUNTER_ASYNC"
export  const DECREMENT_COUNTER_ASYNC ="DECREMENT_COUNTER_ASYNC"


  